### ISSUE TITLE
Slides are not updating on Windows

### ISSUE THREAD

**Issue by msoedov** [msoedov/hacker-slides#7]

**Comment by tractatus** [comment]
I'm also experience this problem but not on Windows rather on Ubuntu 16.04.2 x64.

Could there be a server setting or browser issue, rather than OS? 

Example server output can look like:
`[GIN] 2017/02/27 - 18:40:20 | 404 |       4.962µs | 130.237.114.35 |   GET     /slides/
INFO[1191] Got session                                   path="slides/broad-fog.md"
INFO[1191] Wrote to file                                 file="slides/broad-fog.md" size=777
[GIN] 2017/02/27 - 18:44:13 | 200 |    1.249072ms | 130.237.114.35 |   PUT     /slides.md
INFO[1191] Got session                                   path="slides/broad-fog.md"
[GIN] 2017/02/27 - 18:44:13 | 200 |     654.492µs | 130.237.114.35 |   GET     /slides.md`

But in the browser the slide just blinks and doesn't change.

**Comment by msoedov** [comment]
Can you reproduce it from running from container?

```shell
docker run -it -p 8080:8080  -v $(pwd)/slides:/app/slides msoedov/hacker-slides
```

**Comment by tractatus** [comment]
ok I'll set up docker on this droplet. Just wait a sec.

Thanks!

**Comment by tractatus** [comment]
That did it! Thanks!
